language: java
install:
- bash install.sh
script:
- bash test.sh
before_script:
- bash pull.sh
after_success:
- bash push.sh
env:
  global:
    secure: RJMOCgxLdb5dE9xf+HLfdNGc5aqxjh4F0zBG09fI+R7W7BOTKiPIcVWF2nflRVESX442cDDBfEQO8lDGLGRd6bAHQeap3gfJo/WY4mNSmfJqpRp2zz6YF7SykMfqapZ4CYBgTASr+oRiLM8a02kjecgjnNDlLnXo8gdrRzH8SiM8R5X3nfZsEGxjgNYia+UHK/Lt4I8FWXC0l6CKffymRDDa3sbx/DolxBuNXpkSer9BHdUjSLJnhkQ0cLGE1Tj4ByIbpZSZIEW5WO/RyMVIsX10IZojvNQlVax2RZKkhmLsxGPdoFq/iwj4Qc5vqGeGFPfkxm5QAc2OuYxMGGlsKEjygooS0ymoyuLtLeD2SahlA/mq9VRE1dWRZbaoPdKLRGuIjcTcJ1ue6cjUH9JgQviDDMB4qryOdtA/twruoo1eNrAqGE9600HWqGm0jx8CvarWhY+cTP4OWVzzxAn/KsyFm9uSlBzttezsPHrjAySLzULVdn5um/Q/mRvxZGRxEEtvh109681enCUGagxJ2VlrqvH4HFAEjAcl9Zjv0itQQp996YLnjl83yXvjjR6YlnrDctr5X0ALXxFOLp8CfleNmmrcUciLM9Q8tsSZgIqtTutGVhn9NeEqiLLrb5LA7uFgTYpPrE2Q2ghaGqddS2CvNNkqgZ/q5GMDQoXtJ8U=
